### ISSUE TITLE
may I turn off the error notice when the file not exist?

### ISSUE THREAD

**Issue by mashirozx** [Amaimersion/remove-files-webpack-plugin#10]
![image](https://user-images.githubusercontent.com/16148054/68994738-6b4adc80-08c1-11ea-8de5-043c61cfb810.png)

It's pretty annoying when the file/folder in `after` block not exist, this always show in `--watch` mode. I don't care whether they exists at beginning, I just want to make sure they are removed if they are there.

**Comment by Amaimersion** [comment]
Hello!

Thank you for your feedback. I will add option for this in next update, which i planned to release in this month.

**Comment by mashirozx** [comment]
thanks:kissing_heart:

**Comment by Amaimersion** [comment]
Hello! Sorry for late, i was really busy last days.

Starting from v1,1.4 you can control logs of different levels through `log`, `logWarning`, `logError` and `logDebug` parameters. So, if you want to disable errors and warnings, you can set `logWarning: false; logError: false`.

**Comment by Amaimersion** [comment]
I close this. Feel free to reopen if something is wrong.

**Comment by mashirozx** [comment]
Thank you:kissing_heart:
