### ISSUE TITLE
Cannot silence logs via `stats` in webpack config

### ISSUE THREAD

**Issue by neaumusic** [Amaimersion/remove-files-webpack-plugin#29]
I believe this is pretty self explanatory, it doesn't seem to respect the global webpack.config.js `stats` config for controlling logs

**Comment by neaumusic** [comment]
Ok -- `log` is respected within each sub-config (before / after)
Global `stats` are still not respected afaict

**Comment by Amaimersion** [comment]
Hello!

Thank you for feature request.

Starting from 1.4.3 you can control logging with webpack `stats` parameter.

To do so specify `readWebpackConfiguration: true` in the plugin parameters. By default it is `false`.

[Possible values](https://webpack.js.org/configuration/stats/) are supported: `string`, `boolean`, `{all, errors, warnings}`.

**Comment by Amaimersion** [comment]
Added support for: `{logging}`.
