### ISSUE TITLE
not useful!!!!

### ISSUE THREAD

**Issue by cleverboy32** [Amaimersion/remove-files-webpack-plugin#3]
```
{
                before: {
                    include: ['lib/index.js']
                },
                after: {
                    include: ['index.js'],
                    exclude: ['index.css'],
                }
            }
```
not one file be remove!
is webpack need 4.0???? my webpack is 3.11

**Comment by Amaimersion** [comment]
I fixed it in new version. Please update to `1.1.2` version.

I close this issue because it seems everything is okay now. Feel free to reopen it if you still have any problems with that problem.
