### ISSUE TITLE
Option `Trash` being async

### ISSUE THREAD

**Issue by trynx** [Amaimersion/remove-files-webpack-plugin#32]
Hi :)
First of all thanks for this great plugin

I'm using this plugin in the middle of the plugins execution, and other plugins depend on this plugin output, there was a bug that some file would delete after some time (micro seconds) which would affect the afterwards plugins.
Used the option of 'Trash: true' and didn't expect it to be the problem, found out after some time of hard digging in a comment that the 'Trash' option is async (in function 'handleRemove'),  didn't found any where else that it mention such thing, once it was disable everything worked like magic.

I'm suggest if you could add to the description of the 'Trash' option that it is an async operation ?

**Comment by Amaimersion** [comment]
Hello.

Sorry for your some time of hard digging :)

`trash` is actually an asynchronous and this fact was well-known to me (as you already saw in the code documentation). I forgot to add it in user documentation.

Now it is added since 1.4.4.

Thank you for issue!
