### ISSUE TITLE
item undefined bug

### ISSUE THREAD

**Issue by cespinoza-loga** [Amaimersion/remove-files-webpack-plugin#5]
![image](https://user-images.githubusercontent.com/7131176/57497182-2bfd5c80-729c-11e9-9efb-a61b97f90cfb.png)

**Comment by Amaimersion** [comment]
What a negligence from me 😄. Thank you very much! Please, update to 1.1.3 version.

**Comment by cespinoza-loga** [comment]
Also, this came up trying the example from the Readme.

Setting the folder as `./dist` and the test folders as './css' and './js'. Apparently path detects './css' as absolutePaths, as this routes are detected as not safe. I had to remove the './' from the test folders.
