### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by clecap** [Amaimersion/remove-files-webpack-plugin#8]
The description "Defaults to from which directory is called." of the root parameter is not sufficiently clear. Does this refer to the output directory, to the directory in which the webpack config file is located, to the current working directory of the shell when calling webpack or what? Given some minor quirks in the rest of the description I am a bit sceptical - and particularly for a plugin which permanently deletes files it would be good to have this documented clearly and beyond doubts ... :-)

**Comment by Amaimersion** [comment]
Hello!

Indeed, this part is unclear. I will change this in next several days. Actually i planned do that a month ago, but i just have no time for this. 

>and particularly for a plugin which permanently deletes files

You always can try with `emulate` option which emulates delete process.

**Comment by Amaimersion** [comment]
Hello! Sorry for late – i was really busy.

I close this because i improved the documentation. Feel free to reopen this if something is wrong.
