### ISSUE TITLE
before not working in watch mode

### ISSUE THREAD

**Issue by hannanstd** [Amaimersion/remove-files-webpack-plugin#9]
Hi
when we are using --watch in webpack, before folders will not be removed.

**Comment by Amaimersion** [comment]
Hello!

Will be fixed in next version.

**Comment by Amaimersion** [comment]
Hello! I'm really sorry for too big late – there was many busy things in my life.

Starting from v1.1.4 it is working.

**Comment by Amaimersion** [comment]
I'm closing this. Feel free to reopen it, if something wrong.
